name: base_inertial_parameter
channels:
  - conda-forge
  - robostack-staging
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - casadi
  - pandas
  - ros-humble-ros-base
  - ros-humble-rosbag2-py