/* This file was automatically generated by CasADi 3.7.2+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int ahand_thumb_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_C_fun_checkout(void);
extern "C" void ahand_thumb_C_fun_release(int mem);
extern "C" void ahand_thumb_C_fun_incref(void);
extern "C" void ahand_thumb_C_fun_decref(void);
extern "C" casadi_int ahand_thumb_C_fun_n_in(void);
extern "C" casadi_int ahand_thumb_C_fun_n_out(void);
extern "C" casadi_real ahand_thumb_C_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_C_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_C_fun_SZ_ARG 4
#define ahand_thumb_C_fun_SZ_RES 1
#define ahand_thumb_C_fun_SZ_IW 0
#define ahand_thumb_C_fun_SZ_W 0
extern "C" int ahand_thumb_C_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_C_ddot_fun_checkout(void);
extern "C" void ahand_thumb_C_ddot_fun_release(int mem);
extern "C" void ahand_thumb_C_ddot_fun_incref(void);
extern "C" void ahand_thumb_C_ddot_fun_decref(void);
extern "C" casadi_int ahand_thumb_C_ddot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_C_ddot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_C_ddot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_C_ddot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_C_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_ddot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_C_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_C_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_C_ddot_fun_SZ_ARG 6
#define ahand_thumb_C_ddot_fun_SZ_RES 1
#define ahand_thumb_C_ddot_fun_SZ_IW 0
#define ahand_thumb_C_ddot_fun_SZ_W 0
extern "C" int ahand_thumb_C_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_C_dot_fun_checkout(void);
extern "C" void ahand_thumb_C_dot_fun_release(int mem);
extern "C" void ahand_thumb_C_dot_fun_incref(void);
extern "C" void ahand_thumb_C_dot_fun_decref(void);
extern "C" casadi_int ahand_thumb_C_dot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_C_dot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_C_dot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_C_dot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_C_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_dot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_C_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_C_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_C_dot_fun_SZ_ARG 5
#define ahand_thumb_C_dot_fun_SZ_RES 1
#define ahand_thumb_C_dot_fun_SZ_IW 0
#define ahand_thumb_C_dot_fun_SZ_W 0
extern "C" int ahand_thumb_C_std_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_C_std_fun_checkout(void);
extern "C" void ahand_thumb_C_std_fun_release(int mem);
extern "C" void ahand_thumb_C_std_fun_incref(void);
extern "C" void ahand_thumb_C_std_fun_decref(void);
extern "C" casadi_int ahand_thumb_C_std_fun_n_in(void);
extern "C" casadi_int ahand_thumb_C_std_fun_n_out(void);
extern "C" casadi_real ahand_thumb_C_std_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_C_std_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_C_std_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_std_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_C_std_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_C_std_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_C_std_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_C_std_fun_SZ_ARG 4
#define ahand_thumb_C_std_fun_SZ_RES 1
#define ahand_thumb_C_std_fun_SZ_IW 0
#define ahand_thumb_C_std_fun_SZ_W 0
extern "C" int ahand_thumb_Dl1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_Dl1_fun_checkout(void);
extern "C" void ahand_thumb_Dl1_fun_release(int mem);
extern "C" void ahand_thumb_Dl1_fun_incref(void);
extern "C" void ahand_thumb_Dl1_fun_decref(void);
extern "C" casadi_int ahand_thumb_Dl1_fun_n_in(void);
extern "C" casadi_int ahand_thumb_Dl1_fun_n_out(void);
extern "C" casadi_real ahand_thumb_Dl1_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_Dl1_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_Dl1_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Dl1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Dl1_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_Dl1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_Dl1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_Dl1_fun_SZ_ARG 1
#define ahand_thumb_Dl1_fun_SZ_RES 1
#define ahand_thumb_Dl1_fun_SZ_IW 0
#define ahand_thumb_Dl1_fun_SZ_W 0
extern "C" int ahand_thumb_Dl2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_Dl2_fun_checkout(void);
extern "C" void ahand_thumb_Dl2_fun_release(int mem);
extern "C" void ahand_thumb_Dl2_fun_incref(void);
extern "C" void ahand_thumb_Dl2_fun_decref(void);
extern "C" casadi_int ahand_thumb_Dl2_fun_n_in(void);
extern "C" casadi_int ahand_thumb_Dl2_fun_n_out(void);
extern "C" casadi_real ahand_thumb_Dl2_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_Dl2_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_Dl2_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Dl2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Dl2_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_Dl2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_Dl2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_Dl2_fun_SZ_ARG 1
#define ahand_thumb_Dl2_fun_SZ_RES 1
#define ahand_thumb_Dl2_fun_SZ_IW 0
#define ahand_thumb_Dl2_fun_SZ_W 0
extern "C" int ahand_thumb_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_G_fun_checkout(void);
extern "C" void ahand_thumb_G_fun_release(int mem);
extern "C" void ahand_thumb_G_fun_incref(void);
extern "C" void ahand_thumb_G_fun_decref(void);
extern "C" casadi_int ahand_thumb_G_fun_n_in(void);
extern "C" casadi_int ahand_thumb_G_fun_n_out(void);
extern "C" casadi_real ahand_thumb_G_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_G_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_G_fun_SZ_ARG 4
#define ahand_thumb_G_fun_SZ_RES 1
#define ahand_thumb_G_fun_SZ_IW 0
#define ahand_thumb_G_fun_SZ_W 0
extern "C" int ahand_thumb_G_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_G_ddot_fun_checkout(void);
extern "C" void ahand_thumb_G_ddot_fun_release(int mem);
extern "C" void ahand_thumb_G_ddot_fun_incref(void);
extern "C" void ahand_thumb_G_ddot_fun_decref(void);
extern "C" casadi_int ahand_thumb_G_ddot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_G_ddot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_G_ddot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_G_ddot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_G_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_ddot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_G_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_G_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_G_ddot_fun_SZ_ARG 6
#define ahand_thumb_G_ddot_fun_SZ_RES 1
#define ahand_thumb_G_ddot_fun_SZ_IW 0
#define ahand_thumb_G_ddot_fun_SZ_W 0
extern "C" int ahand_thumb_G_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_G_dot_fun_checkout(void);
extern "C" void ahand_thumb_G_dot_fun_release(int mem);
extern "C" void ahand_thumb_G_dot_fun_incref(void);
extern "C" void ahand_thumb_G_dot_fun_decref(void);
extern "C" casadi_int ahand_thumb_G_dot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_G_dot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_G_dot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_G_dot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_G_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_G_dot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_G_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_G_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_G_dot_fun_SZ_ARG 5
#define ahand_thumb_G_dot_fun_SZ_RES 1
#define ahand_thumb_G_dot_fun_SZ_IW 0
#define ahand_thumb_G_dot_fun_SZ_W 0
extern "C" int ahand_thumb_Ia_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_Ia_fun_checkout(void);
extern "C" void ahand_thumb_Ia_fun_release(int mem);
extern "C" void ahand_thumb_Ia_fun_incref(void);
extern "C" void ahand_thumb_Ia_fun_decref(void);
extern "C" casadi_int ahand_thumb_Ia_fun_n_in(void);
extern "C" casadi_int ahand_thumb_Ia_fun_n_out(void);
extern "C" casadi_real ahand_thumb_Ia_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_Ia_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_Ia_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Ia_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Ia_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_Ia_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_Ia_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_Ia_fun_SZ_ARG 2
#define ahand_thumb_Ia_fun_SZ_RES 1
#define ahand_thumb_Ia_fun_SZ_IW 0
#define ahand_thumb_Ia_fun_SZ_W 0
extern "C" int ahand_thumb_J_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_1_fun_checkout(void);
extern "C" void ahand_thumb_J_1_fun_release(int mem);
extern "C" void ahand_thumb_J_1_fun_incref(void);
extern "C" void ahand_thumb_J_1_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_1_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_1_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_1_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_1_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_1_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_1_fun_SZ_ARG 2
#define ahand_thumb_J_1_fun_SZ_RES 1
#define ahand_thumb_J_1_fun_SZ_IW 0
#define ahand_thumb_J_1_fun_SZ_W 0
extern "C" int ahand_thumb_J_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_2_fun_checkout(void);
extern "C" void ahand_thumb_J_2_fun_release(int mem);
extern "C" void ahand_thumb_J_2_fun_incref(void);
extern "C" void ahand_thumb_J_2_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_2_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_2_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_2_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_2_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_2_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_2_fun_SZ_ARG 2
#define ahand_thumb_J_2_fun_SZ_RES 1
#define ahand_thumb_J_2_fun_SZ_IW 0
#define ahand_thumb_J_2_fun_SZ_W 0
extern "C" int ahand_thumb_J_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_3_fun_checkout(void);
extern "C" void ahand_thumb_J_3_fun_release(int mem);
extern "C" void ahand_thumb_J_3_fun_incref(void);
extern "C" void ahand_thumb_J_3_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_3_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_3_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_3_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_3_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_3_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_3_fun_SZ_ARG 2
#define ahand_thumb_J_3_fun_SZ_RES 1
#define ahand_thumb_J_3_fun_SZ_IW 0
#define ahand_thumb_J_3_fun_SZ_W 0
extern "C" int ahand_thumb_J_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_4_fun_checkout(void);
extern "C" void ahand_thumb_J_4_fun_release(int mem);
extern "C" void ahand_thumb_J_4_fun_incref(void);
extern "C" void ahand_thumb_J_4_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_4_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_4_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_4_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_4_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_4_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_4_fun_SZ_ARG 2
#define ahand_thumb_J_4_fun_SZ_RES 1
#define ahand_thumb_J_4_fun_SZ_IW 0
#define ahand_thumb_J_4_fun_SZ_W 0
extern "C" int ahand_thumb_J_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_5_fun_checkout(void);
extern "C" void ahand_thumb_J_5_fun_release(int mem);
extern "C" void ahand_thumb_J_5_fun_incref(void);
extern "C" void ahand_thumb_J_5_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_5_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_5_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_5_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_5_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_5_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_5_fun_SZ_ARG 3
#define ahand_thumb_J_5_fun_SZ_RES 1
#define ahand_thumb_J_5_fun_SZ_IW 0
#define ahand_thumb_J_5_fun_SZ_W 0
extern "C" int ahand_thumb_J_cm_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_cm_1_fun_checkout(void);
extern "C" void ahand_thumb_J_cm_1_fun_release(int mem);
extern "C" void ahand_thumb_J_cm_1_fun_incref(void);
extern "C" void ahand_thumb_J_cm_1_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_cm_1_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_cm_1_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_cm_1_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_1_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_1_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_cm_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_cm_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_cm_1_fun_SZ_ARG 3
#define ahand_thumb_J_cm_1_fun_SZ_RES 1
#define ahand_thumb_J_cm_1_fun_SZ_IW 0
#define ahand_thumb_J_cm_1_fun_SZ_W 0
extern "C" int ahand_thumb_J_cm_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_cm_2_fun_checkout(void);
extern "C" void ahand_thumb_J_cm_2_fun_release(int mem);
extern "C" void ahand_thumb_J_cm_2_fun_incref(void);
extern "C" void ahand_thumb_J_cm_2_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_cm_2_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_cm_2_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_cm_2_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_2_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_2_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_cm_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_cm_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_cm_2_fun_SZ_ARG 3
#define ahand_thumb_J_cm_2_fun_SZ_RES 1
#define ahand_thumb_J_cm_2_fun_SZ_IW 0
#define ahand_thumb_J_cm_2_fun_SZ_W 0
extern "C" int ahand_thumb_J_cm_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_cm_3_fun_checkout(void);
extern "C" void ahand_thumb_J_cm_3_fun_release(int mem);
extern "C" void ahand_thumb_J_cm_3_fun_incref(void);
extern "C" void ahand_thumb_J_cm_3_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_cm_3_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_cm_3_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_cm_3_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_3_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_3_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_cm_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_cm_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_cm_3_fun_SZ_ARG 3
#define ahand_thumb_J_cm_3_fun_SZ_RES 1
#define ahand_thumb_J_cm_3_fun_SZ_IW 0
#define ahand_thumb_J_cm_3_fun_SZ_W 0
extern "C" int ahand_thumb_J_cm_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_cm_4_fun_checkout(void);
extern "C" void ahand_thumb_J_cm_4_fun_release(int mem);
extern "C" void ahand_thumb_J_cm_4_fun_incref(void);
extern "C" void ahand_thumb_J_cm_4_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_cm_4_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_cm_4_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_cm_4_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_4_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_cm_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_cm_4_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_cm_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_cm_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_cm_4_fun_SZ_ARG 3
#define ahand_thumb_J_cm_4_fun_SZ_RES 1
#define ahand_thumb_J_cm_4_fun_SZ_IW 0
#define ahand_thumb_J_cm_4_fun_SZ_W 0
extern "C" int ahand_thumb_J_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_ee_fun_checkout(void);
extern "C" void ahand_thumb_J_ee_fun_release(int mem);
extern "C" void ahand_thumb_J_ee_fun_incref(void);
extern "C" void ahand_thumb_J_ee_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_ee_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_ee_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_ee_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_ee_fun_SZ_ARG 3
#define ahand_thumb_J_ee_fun_SZ_RES 1
#define ahand_thumb_J_ee_fun_SZ_IW 0
#define ahand_thumb_J_ee_fun_SZ_W 0
extern "C" int ahand_thumb_J_ee_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_ee_ddot_fun_checkout(void);
extern "C" void ahand_thumb_J_ee_ddot_fun_release(int mem);
extern "C" void ahand_thumb_J_ee_ddot_fun_incref(void);
extern "C" void ahand_thumb_J_ee_ddot_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_ee_ddot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_ee_ddot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_ee_ddot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_ddot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_ddot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_ee_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_ee_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_ee_ddot_fun_SZ_ARG 5
#define ahand_thumb_J_ee_ddot_fun_SZ_RES 1
#define ahand_thumb_J_ee_ddot_fun_SZ_IW 0
#define ahand_thumb_J_ee_ddot_fun_SZ_W 0
extern "C" int ahand_thumb_J_ee_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_ee_dot_fun_checkout(void);
extern "C" void ahand_thumb_J_ee_dot_fun_release(int mem);
extern "C" void ahand_thumb_J_ee_dot_fun_incref(void);
extern "C" void ahand_thumb_J_ee_dot_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_ee_dot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_ee_dot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_ee_dot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_dot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_dot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_ee_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_ee_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_ee_dot_fun_SZ_ARG 4
#define ahand_thumb_J_ee_dot_fun_SZ_RES 1
#define ahand_thumb_J_ee_dot_fun_SZ_IW 0
#define ahand_thumb_J_ee_dot_fun_SZ_W 0
extern "C" int ahand_thumb_J_ee_pinv_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_J_ee_pinv_fun_checkout(void);
extern "C" void ahand_thumb_J_ee_pinv_fun_release(int mem);
extern "C" void ahand_thumb_J_ee_pinv_fun_incref(void);
extern "C" void ahand_thumb_J_ee_pinv_fun_decref(void);
extern "C" casadi_int ahand_thumb_J_ee_pinv_fun_n_in(void);
extern "C" casadi_int ahand_thumb_J_ee_pinv_fun_n_out(void);
extern "C" casadi_real ahand_thumb_J_ee_pinv_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_pinv_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_J_ee_pinv_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_pinv_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_J_ee_pinv_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_J_ee_pinv_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_J_ee_pinv_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_J_ee_pinv_fun_SZ_ARG 3
#define ahand_thumb_J_ee_pinv_fun_SZ_RES 1
#define ahand_thumb_J_ee_pinv_fun_SZ_IW 0
#define ahand_thumb_J_ee_pinv_fun_SZ_W 0
extern "C" int ahand_thumb_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_M_fun_checkout(void);
extern "C" void ahand_thumb_M_fun_release(int mem);
extern "C" void ahand_thumb_M_fun_incref(void);
extern "C" void ahand_thumb_M_fun_decref(void);
extern "C" casadi_int ahand_thumb_M_fun_n_in(void);
extern "C" casadi_int ahand_thumb_M_fun_n_out(void);
extern "C" casadi_real ahand_thumb_M_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_M_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_M_fun_SZ_ARG 3
#define ahand_thumb_M_fun_SZ_RES 1
#define ahand_thumb_M_fun_SZ_IW 0
#define ahand_thumb_M_fun_SZ_W 0
extern "C" int ahand_thumb_M_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_M_ddot_fun_checkout(void);
extern "C" void ahand_thumb_M_ddot_fun_release(int mem);
extern "C" void ahand_thumb_M_ddot_fun_incref(void);
extern "C" void ahand_thumb_M_ddot_fun_decref(void);
extern "C" casadi_int ahand_thumb_M_ddot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_M_ddot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_M_ddot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_M_ddot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_M_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_ddot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_M_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_M_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_M_ddot_fun_SZ_ARG 5
#define ahand_thumb_M_ddot_fun_SZ_RES 1
#define ahand_thumb_M_ddot_fun_SZ_IW 0
#define ahand_thumb_M_ddot_fun_SZ_W 0
extern "C" int ahand_thumb_M_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_M_dot_fun_checkout(void);
extern "C" void ahand_thumb_M_dot_fun_release(int mem);
extern "C" void ahand_thumb_M_dot_fun_incref(void);
extern "C" void ahand_thumb_M_dot_fun_decref(void);
extern "C" casadi_int ahand_thumb_M_dot_fun_n_in(void);
extern "C" casadi_int ahand_thumb_M_dot_fun_n_out(void);
extern "C" casadi_real ahand_thumb_M_dot_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_M_dot_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_M_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_M_dot_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_M_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_M_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_M_dot_fun_SZ_ARG 4
#define ahand_thumb_M_dot_fun_SZ_RES 1
#define ahand_thumb_M_dot_fun_SZ_IW 0
#define ahand_thumb_M_dot_fun_SZ_W 0
extern "C" int ahand_thumb_T_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_0_fun_checkout(void);
extern "C" void ahand_thumb_T_0_fun_release(int mem);
extern "C" void ahand_thumb_T_0_fun_incref(void);
extern "C" void ahand_thumb_T_0_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_0_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_0_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_0_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_0_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_0_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_0_fun_SZ_ARG 1
#define ahand_thumb_T_0_fun_SZ_RES 1
#define ahand_thumb_T_0_fun_SZ_IW 0
#define ahand_thumb_T_0_fun_SZ_W 0
extern "C" int ahand_thumb_T_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_1_fun_checkout(void);
extern "C" void ahand_thumb_T_1_fun_release(int mem);
extern "C" void ahand_thumb_T_1_fun_incref(void);
extern "C" void ahand_thumb_T_1_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_1_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_1_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_1_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_1_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_1_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_1_fun_SZ_ARG 1
#define ahand_thumb_T_1_fun_SZ_RES 1
#define ahand_thumb_T_1_fun_SZ_IW 0
#define ahand_thumb_T_1_fun_SZ_W 0
extern "C" int ahand_thumb_T_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_2_fun_checkout(void);
extern "C" void ahand_thumb_T_2_fun_release(int mem);
extern "C" void ahand_thumb_T_2_fun_incref(void);
extern "C" void ahand_thumb_T_2_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_2_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_2_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_2_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_2_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_2_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_2_fun_SZ_ARG 1
#define ahand_thumb_T_2_fun_SZ_RES 1
#define ahand_thumb_T_2_fun_SZ_IW 0
#define ahand_thumb_T_2_fun_SZ_W 0
extern "C" int ahand_thumb_T_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_3_fun_checkout(void);
extern "C" void ahand_thumb_T_3_fun_release(int mem);
extern "C" void ahand_thumb_T_3_fun_incref(void);
extern "C" void ahand_thumb_T_3_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_3_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_3_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_3_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_3_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_3_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_3_fun_SZ_ARG 1
#define ahand_thumb_T_3_fun_SZ_RES 1
#define ahand_thumb_T_3_fun_SZ_IW 0
#define ahand_thumb_T_3_fun_SZ_W 0
extern "C" int ahand_thumb_T_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_4_fun_checkout(void);
extern "C" void ahand_thumb_T_4_fun_release(int mem);
extern "C" void ahand_thumb_T_4_fun_incref(void);
extern "C" void ahand_thumb_T_4_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_4_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_4_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_4_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_4_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_4_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_4_fun_SZ_ARG 1
#define ahand_thumb_T_4_fun_SZ_RES 1
#define ahand_thumb_T_4_fun_SZ_IW 0
#define ahand_thumb_T_4_fun_SZ_W 0
extern "C" int ahand_thumb_T_JOINT_P_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_JOINT_P_fun_checkout(void);
extern "C" void ahand_thumb_T_JOINT_P_fun_release(int mem);
extern "C" void ahand_thumb_T_JOINT_P_fun_incref(void);
extern "C" void ahand_thumb_T_JOINT_P_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_JOINT_P_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_JOINT_P_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_JOINT_P_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_JOINT_P_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_JOINT_P_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_JOINT_P_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_JOINT_P_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_JOINT_P_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_JOINT_P_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_JOINT_P_fun_SZ_ARG 2
#define ahand_thumb_T_JOINT_P_fun_SZ_RES 1
#define ahand_thumb_T_JOINT_P_fun_SZ_IW 0
#define ahand_thumb_T_JOINT_P_fun_SZ_W 0
extern "C" int ahand_thumb_T_JOINT_R_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_JOINT_R_fun_checkout(void);
extern "C" void ahand_thumb_T_JOINT_R_fun_release(int mem);
extern "C" void ahand_thumb_T_JOINT_R_fun_incref(void);
extern "C" void ahand_thumb_T_JOINT_R_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_JOINT_R_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_JOINT_R_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_JOINT_R_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_JOINT_R_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_JOINT_R_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_JOINT_R_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_JOINT_R_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_JOINT_R_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_JOINT_R_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_JOINT_R_fun_SZ_ARG 2
#define ahand_thumb_T_JOINT_R_fun_SZ_RES 1
#define ahand_thumb_T_JOINT_R_fun_SZ_IW 0
#define ahand_thumb_T_JOINT_R_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_0_fun_checkout(void);
extern "C" void ahand_thumb_T_w_0_fun_release(int mem);
extern "C" void ahand_thumb_T_w_0_fun_incref(void);
extern "C" void ahand_thumb_T_w_0_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_0_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_0_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_0_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_0_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_0_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_0_fun_SZ_ARG 1
#define ahand_thumb_T_w_0_fun_SZ_RES 1
#define ahand_thumb_T_w_0_fun_SZ_IW 0
#define ahand_thumb_T_w_0_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_1_fun_checkout(void);
extern "C" void ahand_thumb_T_w_1_fun_release(int mem);
extern "C" void ahand_thumb_T_w_1_fun_incref(void);
extern "C" void ahand_thumb_T_w_1_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_1_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_1_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_1_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_1_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_1_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_1_fun_SZ_ARG 2
#define ahand_thumb_T_w_1_fun_SZ_RES 1
#define ahand_thumb_T_w_1_fun_SZ_IW 0
#define ahand_thumb_T_w_1_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_2_fun_checkout(void);
extern "C" void ahand_thumb_T_w_2_fun_release(int mem);
extern "C" void ahand_thumb_T_w_2_fun_incref(void);
extern "C" void ahand_thumb_T_w_2_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_2_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_2_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_2_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_2_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_2_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_2_fun_SZ_ARG 2
#define ahand_thumb_T_w_2_fun_SZ_RES 1
#define ahand_thumb_T_w_2_fun_SZ_IW 0
#define ahand_thumb_T_w_2_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_3_fun_checkout(void);
extern "C" void ahand_thumb_T_w_3_fun_release(int mem);
extern "C" void ahand_thumb_T_w_3_fun_incref(void);
extern "C" void ahand_thumb_T_w_3_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_3_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_3_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_3_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_3_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_3_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_3_fun_SZ_ARG 2
#define ahand_thumb_T_w_3_fun_SZ_RES 1
#define ahand_thumb_T_w_3_fun_SZ_IW 0
#define ahand_thumb_T_w_3_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_4_fun_checkout(void);
extern "C" void ahand_thumb_T_w_4_fun_release(int mem);
extern "C" void ahand_thumb_T_w_4_fun_incref(void);
extern "C" void ahand_thumb_T_w_4_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_4_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_4_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_4_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_4_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_4_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_4_fun_SZ_ARG 2
#define ahand_thumb_T_w_4_fun_SZ_RES 1
#define ahand_thumb_T_w_4_fun_SZ_IW 0
#define ahand_thumb_T_w_4_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_5_fun_checkout(void);
extern "C" void ahand_thumb_T_w_5_fun_release(int mem);
extern "C" void ahand_thumb_T_w_5_fun_incref(void);
extern "C" void ahand_thumb_T_w_5_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_5_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_5_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_5_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_5_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_5_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_5_fun_SZ_ARG 3
#define ahand_thumb_T_w_5_fun_SZ_RES 1
#define ahand_thumb_T_w_5_fun_SZ_IW 0
#define ahand_thumb_T_w_5_fun_SZ_W 0
extern "C" int ahand_thumb_T_w_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_T_w_ee_fun_checkout(void);
extern "C" void ahand_thumb_T_w_ee_fun_release(int mem);
extern "C" void ahand_thumb_T_w_ee_fun_incref(void);
extern "C" void ahand_thumb_T_w_ee_fun_decref(void);
extern "C" casadi_int ahand_thumb_T_w_ee_fun_n_in(void);
extern "C" casadi_int ahand_thumb_T_w_ee_fun_n_out(void);
extern "C" casadi_real ahand_thumb_T_w_ee_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_ee_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_T_w_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_T_w_ee_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_T_w_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_T_w_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_T_w_ee_fun_SZ_ARG 3
#define ahand_thumb_T_w_ee_fun_SZ_RES 1
#define ahand_thumb_T_w_ee_fun_SZ_IW 0
#define ahand_thumb_T_w_ee_fun_SZ_W 0
extern "C" int ahand_thumb_Yr_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_Yr_fun_checkout(void);
extern "C" void ahand_thumb_Yr_fun_release(int mem);
extern "C" void ahand_thumb_Yr_fun_incref(void);
extern "C" void ahand_thumb_Yr_fun_decref(void);
extern "C" casadi_int ahand_thumb_Yr_fun_n_in(void);
extern "C" casadi_int ahand_thumb_Yr_fun_n_out(void);
extern "C" casadi_real ahand_thumb_Yr_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_Yr_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_Yr_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Yr_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Yr_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_Yr_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_Yr_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_Yr_fun_SZ_ARG 6
#define ahand_thumb_Yr_fun_SZ_RES 1
#define ahand_thumb_Yr_fun_SZ_IW 0
#define ahand_thumb_Yr_fun_SZ_W 0
extern "C" int ahand_thumb_Yr_red_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_Yr_red_fun_checkout(void);
extern "C" void ahand_thumb_Yr_red_fun_release(int mem);
extern "C" void ahand_thumb_Yr_red_fun_incref(void);
extern "C" void ahand_thumb_Yr_red_fun_decref(void);
extern "C" casadi_int ahand_thumb_Yr_red_fun_n_in(void);
extern "C" casadi_int ahand_thumb_Yr_red_fun_n_out(void);
extern "C" casadi_real ahand_thumb_Yr_red_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_Yr_red_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_Yr_red_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Yr_red_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_Yr_red_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_Yr_red_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_Yr_red_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_Yr_red_fun_SZ_ARG 6
#define ahand_thumb_Yr_red_fun_SZ_RES 1
#define ahand_thumb_Yr_red_fun_SZ_IW 0
#define ahand_thumb_Yr_red_fun_SZ_W 0
extern "C" int ahand_thumb_beta_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_beta_fun_checkout(void);
extern "C" void ahand_thumb_beta_fun_release(int mem);
extern "C" void ahand_thumb_beta_fun_incref(void);
extern "C" void ahand_thumb_beta_fun_decref(void);
extern "C" casadi_int ahand_thumb_beta_fun_n_in(void);
extern "C" casadi_int ahand_thumb_beta_fun_n_out(void);
extern "C" casadi_real ahand_thumb_beta_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_beta_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_beta_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_beta_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_beta_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_beta_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_beta_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_beta_fun_SZ_ARG 0
#define ahand_thumb_beta_fun_SZ_RES 1
#define ahand_thumb_beta_fun_SZ_IW 0
#define ahand_thumb_beta_fun_SZ_W 0
extern "C" int ahand_thumb_dl_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_dl_fun_checkout(void);
extern "C" void ahand_thumb_dl_fun_release(int mem);
extern "C" void ahand_thumb_dl_fun_incref(void);
extern "C" void ahand_thumb_dl_fun_decref(void);
extern "C" casadi_int ahand_thumb_dl_fun_n_in(void);
extern "C" casadi_int ahand_thumb_dl_fun_n_out(void);
extern "C" casadi_real ahand_thumb_dl_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_dl_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_dl_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_dl_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_dl_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_dl_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_dl_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_dl_fun_SZ_ARG 2
#define ahand_thumb_dl_fun_SZ_RES 1
#define ahand_thumb_dl_fun_SZ_IW 0
#define ahand_thumb_dl_fun_SZ_W 0
extern "C" int ahand_thumb_dyn2reg_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_dyn2reg_fun_checkout(void);
extern "C" void ahand_thumb_dyn2reg_fun_release(int mem);
extern "C" void ahand_thumb_dyn2reg_fun_incref(void);
extern "C" void ahand_thumb_dyn2reg_fun_decref(void);
extern "C" casadi_int ahand_thumb_dyn2reg_fun_n_in(void);
extern "C" casadi_int ahand_thumb_dyn2reg_fun_n_out(void);
extern "C" casadi_real ahand_thumb_dyn2reg_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_dyn2reg_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_dyn2reg_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_dyn2reg_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_dyn2reg_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_dyn2reg_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_dyn2reg_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_dyn2reg_fun_SZ_ARG 1
#define ahand_thumb_dyn2reg_fun_SZ_RES 1
#define ahand_thumb_dyn2reg_fun_SZ_IW 0
#define ahand_thumb_dyn2reg_fun_SZ_W 0
extern "C" int ahand_thumb_par_KIN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_par_KIN_fun_checkout(void);
extern "C" void ahand_thumb_par_KIN_fun_release(int mem);
extern "C" void ahand_thumb_par_KIN_fun_incref(void);
extern "C" void ahand_thumb_par_KIN_fun_decref(void);
extern "C" casadi_int ahand_thumb_par_KIN_fun_n_in(void);
extern "C" casadi_int ahand_thumb_par_KIN_fun_n_out(void);
extern "C" casadi_real ahand_thumb_par_KIN_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_par_KIN_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_par_KIN_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_par_KIN_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_par_KIN_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_par_KIN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_par_KIN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_par_KIN_fun_SZ_ARG 0
#define ahand_thumb_par_KIN_fun_SZ_RES 1
#define ahand_thumb_par_KIN_fun_SZ_IW 0
#define ahand_thumb_par_KIN_fun_SZ_W 0
extern "C" int ahand_thumb_reg2dyn_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg2dyn_fun_checkout(void);
extern "C" void ahand_thumb_reg2dyn_fun_release(int mem);
extern "C" void ahand_thumb_reg2dyn_fun_incref(void);
extern "C" void ahand_thumb_reg2dyn_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg2dyn_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg2dyn_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg2dyn_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg2dyn_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg2dyn_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg2dyn_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg2dyn_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg2dyn_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg2dyn_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg2dyn_fun_SZ_ARG 1
#define ahand_thumb_reg2dyn_fun_SZ_RES 1
#define ahand_thumb_reg2dyn_fun_SZ_IW 0
#define ahand_thumb_reg2dyn_fun_SZ_W 0
extern "C" int ahand_thumb_reg2red_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg2red_fun_checkout(void);
extern "C" void ahand_thumb_reg2red_fun_release(int mem);
extern "C" void ahand_thumb_reg2red_fun_incref(void);
extern "C" void ahand_thumb_reg2red_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg2red_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg2red_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg2red_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg2red_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg2red_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg2red_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg2red_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg2red_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg2red_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg2red_fun_SZ_ARG 2
#define ahand_thumb_reg2red_fun_SZ_RES 1
#define ahand_thumb_reg2red_fun_SZ_IW 0
#define ahand_thumb_reg2red_fun_SZ_W 0
extern "C" int ahand_thumb_reg_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_C_fun_checkout(void);
extern "C" void ahand_thumb_reg_C_fun_release(int mem);
extern "C" void ahand_thumb_reg_C_fun_incref(void);
extern "C" void ahand_thumb_reg_C_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_C_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_C_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_C_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_C_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_C_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_C_fun_SZ_ARG 4
#define ahand_thumb_reg_C_fun_SZ_RES 1
#define ahand_thumb_reg_C_fun_SZ_IW 0
#define ahand_thumb_reg_C_fun_SZ_W 0
extern "C" int ahand_thumb_reg_C_red_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_C_red_fun_checkout(void);
extern "C" void ahand_thumb_reg_C_red_fun_release(int mem);
extern "C" void ahand_thumb_reg_C_red_fun_incref(void);
extern "C" void ahand_thumb_reg_C_red_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_C_red_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_C_red_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_C_red_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_C_red_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_C_red_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_C_red_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_C_red_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_C_red_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_C_red_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_C_red_fun_SZ_ARG 4
#define ahand_thumb_reg_C_red_fun_SZ_RES 1
#define ahand_thumb_reg_C_red_fun_SZ_IW 0
#define ahand_thumb_reg_C_red_fun_SZ_W 0
extern "C" int ahand_thumb_reg_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_G_fun_checkout(void);
extern "C" void ahand_thumb_reg_G_fun_release(int mem);
extern "C" void ahand_thumb_reg_G_fun_incref(void);
extern "C" void ahand_thumb_reg_G_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_G_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_G_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_G_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_G_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_G_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_G_fun_SZ_ARG 3
#define ahand_thumb_reg_G_fun_SZ_RES 1
#define ahand_thumb_reg_G_fun_SZ_IW 0
#define ahand_thumb_reg_G_fun_SZ_W 0
extern "C" int ahand_thumb_reg_G_red_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_G_red_fun_checkout(void);
extern "C" void ahand_thumb_reg_G_red_fun_release(int mem);
extern "C" void ahand_thumb_reg_G_red_fun_incref(void);
extern "C" void ahand_thumb_reg_G_red_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_G_red_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_G_red_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_G_red_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_G_red_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_G_red_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_G_red_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_G_red_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_G_red_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_G_red_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_G_red_fun_SZ_ARG 3
#define ahand_thumb_reg_G_red_fun_SZ_RES 1
#define ahand_thumb_reg_G_red_fun_SZ_IW 0
#define ahand_thumb_reg_G_red_fun_SZ_W 0
extern "C" int ahand_thumb_reg_Ia_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_Ia_fun_checkout(void);
extern "C" void ahand_thumb_reg_Ia_fun_release(int mem);
extern "C" void ahand_thumb_reg_Ia_fun_incref(void);
extern "C" void ahand_thumb_reg_Ia_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_Ia_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_Ia_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_Ia_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_Ia_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_Ia_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_Ia_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_Ia_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_Ia_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_Ia_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_Ia_fun_SZ_ARG 1
#define ahand_thumb_reg_Ia_fun_SZ_RES 1
#define ahand_thumb_reg_Ia_fun_SZ_IW 0
#define ahand_thumb_reg_Ia_fun_SZ_W 0
extern "C" int ahand_thumb_reg_JTw_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_JTw_fun_checkout(void);
extern "C" void ahand_thumb_reg_JTw_fun_release(int mem);
extern "C" void ahand_thumb_reg_JTw_fun_incref(void);
extern "C" void ahand_thumb_reg_JTw_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_JTw_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_JTw_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_JTw_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_JTw_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_JTw_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_JTw_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_JTw_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_JTw_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_JTw_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_JTw_fun_SZ_ARG 4
#define ahand_thumb_reg_JTw_fun_SZ_RES 1
#define ahand_thumb_reg_JTw_fun_SZ_IW 0
#define ahand_thumb_reg_JTw_fun_SZ_W 0
extern "C" int ahand_thumb_reg_Jdq_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_Jdq_fun_checkout(void);
extern "C" void ahand_thumb_reg_Jdq_fun_release(int mem);
extern "C" void ahand_thumb_reg_Jdq_fun_incref(void);
extern "C" void ahand_thumb_reg_Jdq_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_Jdq_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_Jdq_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_Jdq_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_Jdq_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_Jdq_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_Jdq_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_Jdq_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_Jdq_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_Jdq_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_Jdq_fun_SZ_ARG 4
#define ahand_thumb_reg_Jdq_fun_SZ_RES 1
#define ahand_thumb_reg_Jdq_fun_SZ_IW 0
#define ahand_thumb_reg_Jdq_fun_SZ_W 0
extern "C" int ahand_thumb_reg_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_M_fun_checkout(void);
extern "C" void ahand_thumb_reg_M_fun_release(int mem);
extern "C" void ahand_thumb_reg_M_fun_incref(void);
extern "C" void ahand_thumb_reg_M_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_M_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_M_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_M_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_M_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_M_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_M_fun_SZ_ARG 3
#define ahand_thumb_reg_M_fun_SZ_RES 1
#define ahand_thumb_reg_M_fun_SZ_IW 0
#define ahand_thumb_reg_M_fun_SZ_W 0
extern "C" int ahand_thumb_reg_M_red_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_M_red_fun_checkout(void);
extern "C" void ahand_thumb_reg_M_red_fun_release(int mem);
extern "C" void ahand_thumb_reg_M_red_fun_incref(void);
extern "C" void ahand_thumb_reg_M_red_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_M_red_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_M_red_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_M_red_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_M_red_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_M_red_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_M_red_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_M_red_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_M_red_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_M_red_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_M_red_fun_SZ_ARG 3
#define ahand_thumb_reg_M_red_fun_SZ_RES 1
#define ahand_thumb_reg_M_red_fun_SZ_IW 0
#define ahand_thumb_reg_M_red_fun_SZ_W 0
extern "C" int ahand_thumb_reg_dl_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int ahand_thumb_reg_dl_fun_checkout(void);
extern "C" void ahand_thumb_reg_dl_fun_release(int mem);
extern "C" void ahand_thumb_reg_dl_fun_incref(void);
extern "C" void ahand_thumb_reg_dl_fun_decref(void);
extern "C" casadi_int ahand_thumb_reg_dl_fun_n_in(void);
extern "C" casadi_int ahand_thumb_reg_dl_fun_n_out(void);
extern "C" casadi_real ahand_thumb_reg_dl_fun_default_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_dl_fun_name_in(casadi_int i);
extern "C" const char* ahand_thumb_reg_dl_fun_name_out(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_dl_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* ahand_thumb_reg_dl_fun_sparsity_out(casadi_int i);
extern "C" int ahand_thumb_reg_dl_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int ahand_thumb_reg_dl_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ahand_thumb_reg_dl_fun_SZ_ARG 1
#define ahand_thumb_reg_dl_fun_SZ_RES 1
#define ahand_thumb_reg_dl_fun_SZ_IW 0
#define ahand_thumb_reg_dl_fun_SZ_W 0
