#ifndef THUNDER_ahand_finger_H
#define THUNDER_ahand_finger_H

#include <iostream>
#include <string>
#include <cmath>
#include <eigen3/Eigen/Dense>
#include <yaml-cpp/yaml.h>
#include <fstream>

using std::string;
using std::vector;
using std::map;
using Eigen::MatrixXd;
using Eigen::VectorXd;
using Eigen::Matrix;
using Eigen::Vector;


// ------------------- //
// --- ROBOT CLASS --- //
// ------------------- //

// Contains all the properties, parameters, and functions generated by CadADi
class thunder_ahand_finger{
	private:

		// ------------------ //
		// --- Parameters --- //
		// ------------------ //

		// Jerk
		Vector<double,4> d3q = {0.000000, 0.000000, 0.000000, 0.000000};
		// Snap
		Vector<double,4> d4q = {0.000000, 0.000000, 0.000000, 0.000000};
		// Acceleration
		Vector<double,4> ddq = {0.000000, 0.000000, 0.000000, 0.000000};
		// Acceleration reference
		Vector<double,4> ddqr = {0.000000, 0.000000, 0.000000, 0.000000};
		// Velocity
		Vector<double,4> dq = {0.000000, 0.000000, 0.000000, 0.000000};
		// Velocity reference
		Vector<double,4> dqr = {0.000000, 0.000000, 0.000000, 0.000000};
		// Dynamic parameters
		Vector<double,40> par_DYN = {0.017600, 0.000000, 0.000000, 0.000000, 0.000013, 0.000000, 0.000002, 0.000012, 0.000000, 0.000003, 0.086000, 0.000000, 0.000000, 0.000000, 0.000019, 0.000002, -0.000006, 0.000049, 0.000000, 0.000056, 0.036700, 0.000000, 0.000000, 0.000000, 0.000004, 0.000000, -0.000001, 0.000015, 0.000000, 0.000013, 0.004000, 0.000000, 0.000000, 0.000000, 0.000001, 0.000000, 0.000000, 0.000002, 0.000000, 0.000002};
		// Link friction parameters
		Vector<double,8> par_Dl = {0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000};
		// Link motor inertia parameters
		Vector<double,4> par_Ia = {0.000000, 0.000000, 0.000000, 0.000000};
		// Last link to end-effector frame
		Vector<double,6> par_Ln2EE = {0.040000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Dynamic parameters for regressor
		Vector<double,40> par_REG = {0.017600, 0.000000, 0.000000, 0.000000, 0.000013, 0.000000, 0.000002, 0.000012, 0.000000, 0.000003, 0.086000, 0.000000, 0.000000, 0.000000, 0.000019, 0.000002, -0.000006, 0.000049, 0.000000, 0.000056, 0.036700, 0.000000, 0.000000, 0.000000, 0.000004, 0.000000, -0.000001, 0.000015, 0.000000, 0.000013, 0.004000, 0.000000, 0.000000, 0.000000, 0.000001, 0.000000, 0.000000, 0.000002, 0.000000, 0.000002};
		// Base inertial parameters for reduced regressor.
		Vector<double,26> par_REG_red = {0.000000, 0.000000, 0.000150, 0.001754, 0.000000, -0.000106, 0.000002, -0.000006, 0.000000, 0.000131, 0.000152, 0.000000, -0.000017, 0.000000, -0.000001, 0.000000, 0.000019, 0.000000, 0.000000, 0.000000, -0.000001, 0.000000, 0.000000, 0.000000, 0.000002, 0.000000};
		// Gravity on world frame
		Vector<double,3> par_gravity = {0.000000, 0.000000, -9.810000};
		// World to base frame
		Vector<double,6> par_world2L0 = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Configuration
		Vector<double,4> q = {0.000000, 0.000000, 0.000000, 0.000000};
		// Wrench
		Vector<double,6> w = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};


	public:

		// ------------------ //
		// --- Properties --- //
		// ------------------ //

		// Robot name
		const string robotName = "ahand_finger";

		// Order of the link friction model
		const int Dl_order = 2;
		// Standard number of dynamic parameters per link
		const int STD_PAR_LINK = 10;
		// Type of joints
		const vector<string> jointsType = {"R", "R", "R", "R"};
		// Number of joints
		const int numJoints = 4;
		// Index of first revolute joint
		const int r1 = 0;
		// Index of sequent revolute joint not aligned with r1
		const int r2 = 1;


		// ----------------- //
		// --- Functions --- //
		// ----------------- //

		// Default constructor
		thunder_ahand_finger();

		// get the parameter: d3q
		Vector<double,4> get_d3q();
		// get the parameter: d4q
		Vector<double,4> get_d4q();
		// get the parameter: ddq
		Vector<double,4> get_ddq();
		// get the parameter: ddqr
		Vector<double,4> get_ddqr();
		// get the parameter: dq
		Vector<double,4> get_dq();
		// get the parameter: dqr
		Vector<double,4> get_dqr();
		// get the parameter: par_DYN
		Vector<double,40> get_par_DYN();
		// get the parameter: par_Dl
		Vector<double,8> get_par_Dl();
		// get the parameter: par_Ia
		Vector<double,4> get_par_Ia();
		// get the parameter: par_Ln2EE
		Vector<double,6> get_par_Ln2EE();
		// get the parameter: par_REG
		Vector<double,40> get_par_REG();
		// get the parameter: par_REG_red
		Vector<double,26> get_par_REG_red();
		// get the parameter: par_gravity
		Vector<double,3> get_par_gravity();
		// get the parameter: par_world2L0
		Vector<double,6> get_par_world2L0();
		// get the parameter: q
		Vector<double,4> get_q();
		// get the parameter: w
		Vector<double,6> get_w();
		// set the parameter: d3q
		void set_d3q(Vector<double,4> value);
		// set the parameter: d4q
		void set_d4q(Vector<double,4> value);
		// set the parameter: ddq
		void set_ddq(Vector<double,4> value);
		// set the parameter: ddqr
		void set_ddqr(Vector<double,4> value);
		// set the parameter: dq
		void set_dq(Vector<double,4> value);
		// set the parameter: dqr
		void set_dqr(Vector<double,4> value);
		// set the parameter: par_DYN
		void set_par_DYN(Vector<double,40> value);
		// set the parameter: par_Dl
		void set_par_Dl(Vector<double,8> value);
		// set the parameter: par_Ia
		void set_par_Ia(Vector<double,4> value);
		// set the parameter: par_Ln2EE
		void set_par_Ln2EE(Vector<double,6> value);
		// set the parameter: par_REG
		void set_par_REG(Vector<double,40> value);
		// set the parameter: par_REG_red
		void set_par_REG_red(Vector<double,26> value);
		// set the parameter: par_gravity
		void set_par_gravity(Vector<double,3> value);
		// set the parameter: par_world2L0
		void set_par_world2L0(Vector<double,6> value);
		// set the parameter: q
		void set_q(Vector<double,4> value);
		// set the parameter: w
		void set_w(Vector<double,6> value);

		/**
		 * @brief Save parameters to file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to save ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int save_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Load parameters from file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to load ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int load_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_C();

		/**
		 * @brief Second time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, d3q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_C_ddot();

		/**
		 * @brief Time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_C_dot();

		/**
		 * @brief Classic formulation of the manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_C_std();

		/**
		 * @brief SEA manipulator link damping, order 1
		 * 
		 * - depends on: {par_Dl}
		 */ 
		Eigen::Matrix<double,4,4> get_Dl1();

		/**
		 * @brief SEA manipulator link damping, order 2
		 * 
		 * - depends on: {par_Dl}
		 */ 
		Eigen::Matrix<double,4,4> get_Dl2();

		/**
		 * @brief Manipulator gravity terms
		 * 
		 * - depends on: {q, par_world2L0, par_gravity, par_DYN}
		 */ 
		Eigen::Matrix<double,4,1> get_G();

		/**
		 * @brief Second time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, ddq, par_world2L0, par_gravity, par_DYN}
		 */ 
		Eigen::Matrix<double,4,1> get_G_ddot();

		/**
		 * @brief Time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, par_world2L0, par_gravity, par_DYN}
		 */ 
		Eigen::Matrix<double,4,1> get_G_dot();

		/**
		 * @brief Manipulator motor inertia torque
		 * 
		 * - depends on: {ddq, par_Ia}
		 */ 
		Eigen::Matrix<double,4,1> get_Ia();

		/**
		 * @brief Jacobian of frame 1
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,6,4> get_J_1();

		/**
		 * @brief Jacobian of frame 2
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,6,4> get_J_2();

		/**
		 * @brief Jacobian of frame 3
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,6,4> get_J_3();

		/**
		 * @brief Jacobian of frame 4
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,6,4> get_J_4();

		/**
		 * @brief Jacobian of frame 5
		 * 
		 * - depends on: {q, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,4> get_J_5();

		/**
		 * @brief Jacobian of center of mass of link 1
		 * 
		 * - depends on: {q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,6,4> get_J_cm_1();

		/**
		 * @brief Jacobian of center of mass of link 2
		 * 
		 * - depends on: {q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,6,4> get_J_cm_2();

		/**
		 * @brief Jacobian of center of mass of link 3
		 * 
		 * - depends on: {q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,6,4> get_J_cm_3();

		/**
		 * @brief Jacobian of center of mass of link 4
		 * 
		 * - depends on: {q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,6,4> get_J_cm_4();

		/**
		 * @brief Jacobian of the end-effector
		 * 
		 * - depends on: {q, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,4> get_J_ee();

		/**
		 * @brief Time second derivative of jacobian matrix
		 * 
		 * - depends on: {q, dq, ddq, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,4> get_J_ee_ddot();

		/**
		 * @brief Time derivative of jacobian matrix
		 * 
		 * - depends on: {q, dq, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,4> get_J_ee_dot();

		/**
		 * @brief Pseudo-Inverse of jacobian matrix
		 * 
		 * - depends on: {q, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,6> get_J_ee_pinv();

		/**
		 * @brief Manipulator mass matrix
		 * 
		 * - depends on: {q, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_M();

		/**
		 * @brief Second time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, ddq, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_M_ddot();

		/**
		 * @brief Time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, par_world2L0, par_DYN}
		 */ 
		Eigen::Matrix<double,4,4> get_M_dot();

		/**
		 * @brief relative transformation from frame world to base
		 * 
		 * - depends on: {par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_0();

		/**
		 * @brief relative transformation from frame0to frame 1
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_1();

		/**
		 * @brief relative transformation from frame1to frame 2
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_2();

		/**
		 * @brief relative transformation from frame2to frame 3
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_3();

		/**
		 * @brief relative transformation from frame3to frame 4
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_4();

		/**
		 * @brief Template transformation of general prismatic joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param [axis_0, axis_1, axis_2] Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_P(Vector<double,1> q_joint, Vector<double,3> axes);

		/**
		 * @brief Template transformation of general rotoidal joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param [axis_0, axis_1, axis_2] Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_R(Vector<double,1> q_joint, Vector<double,3> axes);

		/**
		 * @brief absolute transformation from frame world to base
		 * 
		 * - depends on: {par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_0();

		/**
		 * @brief absolute transformation from frame base to frame 1
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_1();

		/**
		 * @brief absolute transformation from frame base to frame 2
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_2();

		/**
		 * @brief absolute transformation from frame base to frame 3
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_3();

		/**
		 * @brief absolute transformation from frame base to frame 4
		 * 
		 * - depends on: {q, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_4();

		/**
		 * @brief absolute transformation from frame base to end_effector
		 * 
		 * - depends on: {q, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_5();

		/**
		 * @brief absolute transformation from frame 0 to end_effector
		 * 
		 * - depends on: {q, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_ee();

		/**
		 * @brief Manipulator regressor matrix
		 * 
		 * - depends on: {q, dq, dqr, ddqr, par_world2L0, par_gravity}
		 */ 
		Eigen::Matrix<double,4,40> get_Yr();

		/**
		 * @brief Regressor defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, dq, dqr, ddqr, par_world2L0, par_gravity}
		 */ 
		Eigen::Matrix<double,4,26> get_Yr_red();

		/**
		 * @brief linear relationship between full dyn parameters and the reduced set. beta s.t. par_red = beta*par.
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,26,44> get_beta();

		/**
		 * @brief Manipulator link friction
		 * 
		 * - depends on: {dq, par_Dl}
		 */ 
		Eigen::Matrix<double,4,1> get_dl();

		/**
		 * @brief Conversion from dynamic to regressor parameters
		 * 
		 * - depends on: {par_DYN}
		 */ 
		Eigen::Matrix<double,40,1> get_dyn2reg();

		/**
		 * @brief Internal kinematic parameters.
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,24,1> get_par_KIN();

		/**
		 * @brief Conversion from regressor to dynamic parameters
		 * 
		 * - depends on: {par_REG}
		 */ 
		Eigen::Matrix<double,40,1> get_reg2dyn();

		/**
		 * @brief Conversion from regressor to base inertial parameters.
		 * 
		 * - depends on: {par_REG, par_Ia}
		 */ 
		Eigen::Matrix<double,26,1> get_reg2red();

		/**
		 * @brief Regressor matrix of term C*dqr
		 * 
		 * - depends on: {q, dq, dqr, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,40> get_reg_C();

		/**
		 * @brief Regressor of centripetal defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, dq, dqr, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,24> get_reg_C_red();

		/**
		 * @brief Regressor matrix of term G
		 * 
		 * - depends on: {q, par_world2L0, par_gravity}
		 */ 
		Eigen::Matrix<double,4,40> get_reg_G();

		/**
		 * @brief Regressor of gravity defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, par_world2L0, par_gravity}
		 */ 
		Eigen::Matrix<double,4,24> get_reg_G_red();

		/**
		 * @brief Regressor matrix of the motor inertia
		 * 
		 * - depends on: {ddq}
		 */ 
		Eigen::Matrix<double,4,4> get_reg_Ia();

		/**
		 * @brief Regressor matrix of the quantity J^T*w
		 * 
		 * - depends on: {q, w, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,12> get_reg_JTw();

		/**
		 * @brief Regressor matrix of the quantity J*dq
		 * 
		 * - depends on: {q, dq, par_world2L0, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,12> get_reg_Jdq();

		/**
		 * @brief Regressor matrix of term M*ddqr
		 * 
		 * - depends on: {q, ddqr, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,40> get_reg_M();

		/**
		 * @brief Regressor of masses defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, ddqr, par_world2L0}
		 */ 
		Eigen::Matrix<double,4,24> get_reg_M_red();

		/**
		 * @brief Regressor matrix of the link friction
		 * 
		 * - depends on: {dq}
		 */ 
		Eigen::Matrix<double,4,8> get_reg_dl();

};
#endif
