robot:
  path: '/home/leo/Desktop/Base Inertial Parameter/src/config/previous_param_identif/ahand_thumb_par.yaml'

trajectory:
  type: 'ros2'
  bag: '/home/leo/Desktop/allegro_hand_ros2_ws/workdir/allegro_hand_thumb_2traject_bag'
  topic: '/allegroHand_0/joint_states'
  joints: ['joint_12_0', 'joint_13_0', 'joint_14_0', 'joint_15_0']  # Thumb joints
  interval: [0, 100000] # [s]

processing:
  cut_off_frequency: 30 # [rad/s]
  butterworth_order: 5
  apply_decimation: true
  decimate_factor: 10

identification:
  method: 'WLS|prior' # OLS, WLS, OLS|prior, WLS|prior
  #conditioning_ratio: 54 # truncate SVD inverse by forcing this conditioning ( Default: None)

  positive_threshold: 1e-16 # positive threshold for constrained problem definition 
  weight:
    loss: 1 # gain factor for base parameters optimization

    mass: 1e-3     # as mass std.dev [Kg]
    CoM: 1e-3      # as CoM std.dev [m]
    inertia: 1e-16  # as Inertia std.dev [Kg/m^2]

    link: [1, 1, 1, 1]