robot:
  path: '/home/leo/Desktop/Base Inertial Parameter/src/config/previous_param_identif/ahand_finger_par.yaml'

trajectory:
  type: 'ros2'
  bag: '/home/leo/Desktop/allegro_hand_ros2_ws/workdir/allegro_hand_4traject_bag'
  topic: '/allegroHand_0/joint_states'
  joints: ['joint_4_0', 'joint_5_0', 'joint_6_0', 'joint_7_0']  # Middle joints
  interval: [0, 100000] # [s]

processing:
  cut_off_frequency: 30 # [rad/s]
  butterworth_order: 5
  apply_decimation: true
  decimate_factor: 10
  compute_velocities: true # wheter use or compute joint velocities

identification:
  method: 'WLS|prior' # OLS, WLS, OLS|prior, WLS|prior
  #conditioning_ratio: 54 # truncate SVD inverse by forcing this conditioning ( Default: None)

  positive_threshold: 1e-10 # positive threshold for constrained problem definition 
  weight:
    loss: 1 # gain factor for base parameters optimization

    mass: 1e-3     # as mass std.dev [Kg]
    CoM: 1e-3      # as CoM std.dev [m]
    inertia: 1e-16  # as Inertia std.dev [Kg/m^2]

    link: [1, 1, 1, 1]