robot:
  path: '/home/leo/Desktop/Base Inertial Parameter/src/thunder/franka_generatedFiles/param/franka_par.yaml'
  #path: '/home/leo/Desktop/Base Inertial Parameter/src/thunder/franka_generatedFiles/param/franka_SH_par.yaml' 

trajectory:
  type: 'ros2'

  #bag: './rosbag/computed_torque_60s' # <-- Empty
  bag: './rosbag/panda_softhand_computed_torque_50s_v3' # <-- Softhand, s_max = 78383417.82606867
  #bag: './rosbag/softhand_sinusoidal_CT' # <-- Softhand (NEW),           s_max =  4676179.1383352205, ma cond 20x better
  #bag: './rosbag/softhand_chirp_CT' # <-- Softhand,                     s_max = 41834365.32928588

  topic: '/computed_torque_controller/joint_states'

  interval: [25, 55] # [s]
  joints: ['panda_joint1', 'panda_joint2', 'panda_joint3', 'panda_joint4', 'panda_joint5', 'panda_joint6', 'panda_joint7']


processing:
  pipeline:   # Which pipeline apply for data processing ['filtering','differentiating','decimating'] 
     - 'decimating'
     - 'filtering'
     - 'differentiating'
     - 'differentiating'
     - 'filtering'
  cut_off_frequency: 30 #35 [rad/s]
  compute_velocities: true
  butterworth_order: 5 #5
  apply_decimation: false
  decimate_factor: 10


identification:
  method: 'WLS' # OLS, WLS, OLS|prior, WLS|prior
  #conditioning_ratio: 54 # truncate SVD inverse by forcing this conditioning (Default: None)

  optimization: 'SA'  # 'ipopt', 'SA' - Optimization method for maximum-likelihood estimation
  # Simulated annealing ----
  k: 10               # number of outer iteration for simulated annealing solver
  Q: 100              # number of iteration in simmulated annealing


  # CasADi optimizer ----
  # positive_threshold: 1e-10 # positive threshold for constrained problem definition
  # inertia_scale_factor: 1


  weight:
    loss: 1 # gain factor for base parameters optimization

    mass: 1e-3     # as mass std.dev [Kg]
    CoM: 1e-3      # as CoM std.dev [m]
    inertia: 1e-3  # as Inertia std.dev [Kg/m^2]

    link: [1, 1, 1, 1, 1, 1, 1e-2]
