#ifndef THUNDER_franka_H
#define THUNDER_franka_H

#include <iostream>
#include <string>
#include <cmath>
#include <eigen3/Eigen/Dense>
#include <yaml-cpp/yaml.h>
#include <fstream>

using std::string;
using std::vector;
using std::map;
using Eigen::MatrixXd;
using Eigen::VectorXd;
using Eigen::Matrix;
using Eigen::Vector;


// ------------------- //
// --- ROBOT CLASS --- //
// ------------------- //

// Contains all the properties, parameters, and functions generated by CadADi
class thunder_franka{
	private:

		// ------------------ //
		// --- Parameters --- //
		// ------------------ //

		// Jerk
		Vector<double,7> d3q = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Snap
		Vector<double,7> d4q = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Acceleration
		Vector<double,7> ddq = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Acceleration reference
		Vector<double,7> ddqr = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Velocity
		Vector<double,7> dq = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Velocity reference
		Vector<double,7> dqr = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Dynamic parameters
		Vector<double,70> par_DYN = {4.970684, 0.003875, 0.002081, -0.047620, 0.703370, -0.000139, 0.006772, 0.706610, 0.019169, 0.009117, 0.646926, -0.003141, -0.028720, 0.003495, 0.007962, -0.003925, 0.010254, 0.028110, 0.000704, 0.025995, 3.228604, 0.027518, 0.039252, -0.066502, 0.037242, -0.004761, -0.011396, 0.036155, -0.012805, 0.010830, 3.587895, -0.053170, 0.104419, 0.027454, 0.025853, 0.007796, -0.001332, 0.019552, 0.008641, 0.028323, 1.225946, -0.011953, 0.041065, -0.038437, 0.035549, -0.002117, -0.004037, 0.029474, 0.000229, 0.008627, 1.666555, 0.060149, -0.014117, -0.010517, 0.001964, 0.000109, -0.001158, 0.004354, 0.000341, 0.005433, 0.735522, 0.010517, -0.004252, -0.045403, 0.012516, -0.000428, -0.001196, 0.010027, -0.000741, 0.004815};
		// Link friction parameters
		Vector<double,14> par_Dl = {0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000, 0.100000, 0.010000};
		// Last link to end-effector frame
		Vector<double,6> par_Ln2EE = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Dynamic parameters for regressor
		Vector<double,70> par_REG = {4.970684, 0.019261, 0.010344, -0.236704, 0.714663, -0.000179, 0.007689, 0.717956, 0.019662, 0.009213, 0.646926, -0.002032, -0.018580, 0.002261, 0.008504, -0.003983, 0.010261, 0.028124, 0.000769, 0.026535, 3.228604, 0.088845, 0.126729, -0.214709, 0.056495, -0.008248, -0.005488, 0.052878, -0.004377, 0.018249, 3.587895, -0.190768, 0.374644, 0.098502, 0.067677, 0.027716, 0.003905, 0.032399, -0.001644, 0.077586, 1.225946, -0.014654, 0.050343, -0.047122, 0.039428, -0.001515, -0.004600, 0.031460, 0.002164, 0.010870, 1.666555, 0.100242, -0.023527, -0.017527, 0.002480, 0.001524, -0.000104, 0.010568, 0.000094, 0.011795, 0.735522, 0.007735, -0.003127, -0.033395, 0.014046, -0.000395, -0.000845, 0.011625, -0.000883, 0.004910};
		// Base inertial parameters for reduced regressor.
		Vector<double,43> par_REG_red = {0.037337, -0.002032, -3.104340, 0.989623, -0.003983, 0.010261, 0.000769, 1.035779, 0.684158, 0.028227, 0.011596, -0.000122, -0.005488, -0.004377, 0.124455, -0.490080, 1.720684, 0.540829, 0.138764, 0.003905, -0.001644, 0.632524, -0.014654, 0.067871, 0.024231, -0.001515, -0.004600, 0.002164, 0.027133, 0.164968, -0.068833, -0.000884, 0.005511, -0.000104, 0.000094, 0.030390, 0.007735, -0.003127, 0.002421, -0.000395, -0.000845, -0.000883, 0.004910};
		// Configuration
		Vector<double,7> q = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};
		// Wrench
		Vector<double,6> w = {0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000};


	public:

		// ------------------ //
		// --- Properties --- //
		// ------------------ //

		// Robot name
		const string robotName = "franka";

		// Order of the link friction model
		const int Dl_order = 2;
		// Standard number of dynamic parameters per link
		const int STD_PAR_LINK = 10;
		// Type of joints
		const vector<string> jointsType = {"R", "R", "R", "R", "R", "R", "R"};
		// Number of joints
		const int numJoints = 7;
		// Index of first revolute joint
		const int r1 = 0;
		// Index of sequent revolute joint not aligned with r1
		const int r2 = 1;


		// ----------------- //
		// --- Functions --- //
		// ----------------- //

		// Default constructor
		thunder_franka();

		// get the parameter: d3q
		Vector<double,7> get_d3q();
		// get the parameter: d4q
		Vector<double,7> get_d4q();
		// get the parameter: ddq
		Vector<double,7> get_ddq();
		// get the parameter: ddqr
		Vector<double,7> get_ddqr();
		// get the parameter: dq
		Vector<double,7> get_dq();
		// get the parameter: dqr
		Vector<double,7> get_dqr();
		// get the parameter: par_DYN
		Vector<double,70> get_par_DYN();
		// get the parameter: par_Dl
		Vector<double,14> get_par_Dl();
		// get the parameter: par_Ln2EE
		Vector<double,6> get_par_Ln2EE();
		// get the parameter: par_REG
		Vector<double,70> get_par_REG();
		// get the parameter: par_REG_red
		Vector<double,43> get_par_REG_red();
		// get the parameter: q
		Vector<double,7> get_q();
		// get the parameter: w
		Vector<double,6> get_w();
		// set the parameter: d3q
		void set_d3q(Vector<double,7> value);
		// set the parameter: d4q
		void set_d4q(Vector<double,7> value);
		// set the parameter: ddq
		void set_ddq(Vector<double,7> value);
		// set the parameter: ddqr
		void set_ddqr(Vector<double,7> value);
		// set the parameter: dq
		void set_dq(Vector<double,7> value);
		// set the parameter: dqr
		void set_dqr(Vector<double,7> value);
		// set the parameter: par_DYN
		void set_par_DYN(Vector<double,70> value);
		// set the parameter: par_Dl
		void set_par_Dl(Vector<double,14> value);
		// set the parameter: par_Ln2EE
		void set_par_Ln2EE(Vector<double,6> value);
		// set the parameter: par_REG
		void set_par_REG(Vector<double,70> value);
		// set the parameter: par_REG_red
		void set_par_REG_red(Vector<double,43> value);
		// set the parameter: q
		void set_q(Vector<double,7> value);
		// set the parameter: w
		void set_w(Vector<double,6> value);

		/**
		 * @brief Save parameters to file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to save ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int save_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Load parameters from file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to load ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int load_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C();

		/**
		 * @brief Second time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, d3q, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_ddot();

		/**
		 * @brief Time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_dot();

		/**
		 * @brief Classic formulation of the manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_std();

		/**
		 * @brief SEA manipulator link damping, order 1
		 * 
		 * - depends on: {par_Dl}
		 */ 
		Eigen::Matrix<double,7,7> get_Dl1();

		/**
		 * @brief SEA manipulator link damping, order 2
		 * 
		 * - depends on: {par_Dl}
		 */ 
		Eigen::Matrix<double,7,7> get_Dl2();

		/**
		 * @brief Manipulator gravity terms
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G();

		/**
		 * @brief Second time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, ddq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G_ddot();

		/**
		 * @brief Time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G_dot();

		/**
		 * @brief Jacobian of frame 1
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_1();

		/**
		 * @brief Jacobian of frame 2
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_2();

		/**
		 * @brief Jacobian of frame 3
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_3();

		/**
		 * @brief Jacobian of frame 4
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_4();

		/**
		 * @brief Jacobian of frame 5
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_5();

		/**
		 * @brief Jacobian of frame 6
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_6();

		/**
		 * @brief Jacobian of frame 7
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,6,7> get_J_7();

		/**
		 * @brief Jacobian of frame 8
		 * 
		 * - depends on: {q, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,7> get_J_8();

		/**
		 * @brief Jacobian of center of mass of link 1
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_1();

		/**
		 * @brief Jacobian of center of mass of link 2
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_2();

		/**
		 * @brief Jacobian of center of mass of link 3
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_3();

		/**
		 * @brief Jacobian of center of mass of link 4
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_4();

		/**
		 * @brief Jacobian of center of mass of link 5
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_5();

		/**
		 * @brief Jacobian of center of mass of link 6
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_6();

		/**
		 * @brief Jacobian of center of mass of link 7
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_7();

		/**
		 * @brief Jacobian of the end-effector
		 * 
		 * - depends on: {q, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,7> get_J_ee();

		/**
		 * @brief Time second derivative of jacobian matrix
		 * 
		 * - depends on: {q, dq, ddq, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,7> get_J_ee_ddot();

		/**
		 * @brief Time derivative of jacobian matrix
		 * 
		 * - depends on: {q, dq, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,7> get_J_ee_dot();

		/**
		 * @brief Pseudo-Inverse of jacobian matrix
		 * 
		 * - depends on: {q, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,7,6> get_J_ee_pinv();

		/**
		 * @brief Manipulator mass matrix
		 * 
		 * - depends on: {q, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M();

		/**
		 * @brief Second time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, ddq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M_ddot();

		/**
		 * @brief Time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M_dot();

		/**
		 * @brief relative transformation from frame world to base
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_0();

		/**
		 * @brief relative transformation from frame0to frame 1
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_1();

		/**
		 * @brief relative transformation from frame1to frame 2
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_2();

		/**
		 * @brief relative transformation from frame2to frame 3
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_3();

		/**
		 * @brief relative transformation from frame3to frame 4
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_4();

		/**
		 * @brief relative transformation from frame4to frame 5
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_5();

		/**
		 * @brief relative transformation from frame5to frame 6
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_6();

		/**
		 * @brief relative transformation from frame6to frame 7
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_7();

		/**
		 * @brief Template transformation of general prismatic joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param [axis_0, axis_1, axis_2] Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_P(Vector<double,1> q_joint, Vector<double,3> axes);

		/**
		 * @brief Template transformation of general rotoidal joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param [axis_0, axis_1, axis_2] Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_R(Vector<double,1> q_joint, Vector<double,3> axes);

		/**
		 * @brief absolute transformation from frame world to base
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_0();

		/**
		 * @brief absolute transformation from frame base to frame 1
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_1();

		/**
		 * @brief absolute transformation from frame base to frame 2
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_2();

		/**
		 * @brief absolute transformation from frame base to frame 3
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_3();

		/**
		 * @brief absolute transformation from frame base to frame 4
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_4();

		/**
		 * @brief absolute transformation from frame base to frame 5
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_5();

		/**
		 * @brief absolute transformation from frame base to frame 6
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_6();

		/**
		 * @brief absolute transformation from frame base to frame 7
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_7();

		/**
		 * @brief absolute transformation from frame base to end_effector
		 * 
		 * - depends on: {q, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_8();

		/**
		 * @brief absolute transformation from frame 0 to end_effector
		 * 
		 * - depends on: {q, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_ee();

		/**
		 * @brief Manipulator regressor matrix
		 * 
		 * - depends on: {q, dq, dqr, ddqr}
		 */ 
		Eigen::Matrix<double,7,70> get_Yr();

		/**
		 * @brief Regressor defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, dq, dqr, ddqr}
		 */ 
		Eigen::Matrix<double,7,43> get_Yr_red();

		/**
		 * @brief linear relationship between full dyn parameters and the reduced set. beta s.t. par_red = beta*par.
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,43,70> get_beta();

		/**
		 * @brief Manipulator link friction
		 * 
		 * - depends on: {dq, par_Dl}
		 */ 
		Eigen::Matrix<double,7,1> get_dl();

		/**
		 * @brief Conversion from dynamic to regressor parameters
		 * 
		 * - depends on: {par_DYN}
		 */ 
		Eigen::Matrix<double,70,1> get_dyn2reg();

		/**
		 * @brief Internal kinematic parameters.
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,42,1> get_par_KIN();

		/**
		 * @brief Conversion from regressor to dynamic parameters
		 * 
		 * - depends on: {par_REG}
		 */ 
		Eigen::Matrix<double,70,1> get_reg2dyn();

		/**
		 * @brief Conversion from regressor to base inertial parameters.
		 * 
		 * - depends on: {par_REG}
		 */ 
		Eigen::Matrix<double,43,1> get_reg2red();

		/**
		 * @brief Regressor matrix of term C*dqr
		 * 
		 * - depends on: {q, dq, dqr}
		 */ 
		Eigen::Matrix<double,7,70> get_reg_C();

		/**
		 * @brief Regressor of centripetal defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, dq, dqr}
		 */ 
		Eigen::Matrix<double,7,43> get_reg_C_red();

		/**
		 * @brief Regressor matrix of term G
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,7,70> get_reg_G();

		/**
		 * @brief Regressor of gravity defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q}
		 */ 
		Eigen::Matrix<double,7,43> get_reg_G_red();

		/**
		 * @brief Regressor matrix of the quantity J^T*w
		 * 
		 * - depends on: {q, w, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,7,6> get_reg_JTw();

		/**
		 * @brief Regressor matrix of the quantity J*dq
		 * 
		 * - depends on: {q, dq, par_Ln2EE}
		 */ 
		Eigen::Matrix<double,6,6> get_reg_Jdq();

		/**
		 * @brief Regressor matrix of term M*ddqr
		 * 
		 * - depends on: {q, ddqr}
		 */ 
		Eigen::Matrix<double,7,70> get_reg_M();

		/**
		 * @brief Regressor of masses defined w.r.t the set of base iniertial parameters.
		 * 
		 * - depends on: {q, ddqr}
		 */ 
		Eigen::Matrix<double,7,43> get_reg_M_red();

		/**
		 * @brief Regressor matrix of the link friction
		 * 
		 * - depends on: {dq}
		 */ 
		Eigen::Matrix<double,7,14> get_reg_dl();

};
#endif
